### ISSUE TITLE
PhoneVR doesn't use full screen area (including notch)

### ISSUE THREAD

**Issue by tapafon** [PhoneVR-Developers/PhoneVR#102]
I mean, even on a custom ROM without any Xiaomi crap, I still have the cropped and shifted image next to my notch.

_Originally posted by @Mineplayerminer in https://github.com/ShootingKing-AM/PhoneVR/issues/88#issuecomment-1319661994_
            
There are only 3 apps that don't have that issue:
1. Youtube in "Watch in Cardboard" mode.
2. RiftCat Vridge (as long as I don't use legacy backend, which doesn't have reprojection).
3. Home Theater VR by blevok (after recent updates)

**Comment by ShootingKing-AM** [comment]
Need more details, do use the issue templates. Which Custom ROM? Which Android version? Which phone ? Screenshots?

**Comment by ShootingKing-AM** [comment]
> Redmi Note 9. I tried MIUI 12.5.1 (Android 11) and Project Elixir 1.7 and 3.4 (Android 13 build). I can try making the logs. I've already sent out the screenshots before. There was a black bar on the side of the screen where the notch is located. It seems like the app ignored the fullscreen mode. I have even tried making my own cardboard configs but didn't work.

Thanks for your reply @Mineplayerminer. Can you link me to the screenshots please ?

**Comment by Mineplayerminer** [comment]
> Member

Heyy. I finally found the issue I was talking about. I realized it was already closed.
https://github.com/PhoneVR-Developers/PhoneVR/issues/82 issue #82.

**Comment by ShootingKing-AM** [comment]
It's good that it doesn't use full-screen right ? Else there would be a black spot in one of those vr circles. If you are using cardboard viewer or anything you need adjust your phone so that the white line on screen is in center.

Why should it use full-screen?

**Comment by kotleni** [comment]
@ShootingKing-AM I have same problem now, with my Redmi Note 9 stock firmware.

**Comment by kotleni** [comment]
![image](https://github.com/user-attachments/assets/bebef14b-88c4-46c6-8216-833f8976df99)
Check left side of image.

**Comment by kotleni** [comment]
Here is official documentation about cutouts.
https://developer.android.com/develop/ui/views/layout/display-cutout

**Comment by ShootingKing-AM** [comment]
> ![image](https://private-user-images.githubusercontent.com/38311102/355980143-bebef14b-88c4-46c6-8216-833f8976df99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNjkwODYsIm5iZiI6MTcyMzA2ODc4NiwicGF0aCI6Ii8zODMxMTEwMi8zNTU5ODAxNDMtYmViZWYxNGItODhjNC00NmM2LTgyMTYtODMzZjg5NzZkZjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDIyMTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NzVlZDlmZmMwZmE5NzIxNGQ1MTA4YWQ5YmRiZTRhZDkxYTVjMDU1MDI5ZDQ5Y2U3NjdlZGRmODY1ODFjNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PmmYFIQQxZa-LeR-zbyWreDqcGefJTX5pLscCo5opAQ) Check left side of image.

So its correct right ? am assuming the left side black portion is where you are having your Front camera etc.

**Comment by Mineplayerminer** [comment]
The same thing happens almost on all Android phones with camera cutouts. I've tested it further on Redmi Note 7, Pixel 6a and 8, with the same results.

**Comment by ShootingKing-AM** [comment]
> The same thing happens almost on all Android phones with camera cutouts. I've tested it further on Redmi Note 7, Pixel 6a and 8, with the same results.

I dont understand your expectation. Or the cutout users expectations. We have to leave the cutout area black, we cant render onto the cutout area right ? In my opinion PhoneVR is working as it should, the black area is to be left out since there are some cameras etc.

**Comment by tapafon** [comment]
> > The same thing happens almost on all Android phones with camera cutouts. I've tested it further on Redmi Note 7, Pixel 6a and 8, with the same results.
> 
> I dont understand your expectation. Or the cutout users expectations. We have to leave the cutout area black, we cant render onto the cutout area right ? In my opinion PhoneVR is working as it should, the black area is to be left out since there are some cameras etc.

Since cutout area isn't used, image is divided not in the center of actual screen. And when phone is in headset, I can see part of left eye image with right eye, and black stripe with my left eye.
RiftCat renders onto the full screen, including black area.

**Comment by tapafon** [comment]
> Need more details, do use the issue templates. Which Custom ROM? Which Android version? Which phone ? Screenshots? Logs (they may have some errors) ?
> 
> Also what would be the expectation ? We ofcourse shouldn't use notch area right ? The only thing about notched screens is that we have to offset the entire phone in the cardboar/vrBox we might use i guess ?

The phone is Mi 10T Lite. Originally I used MIUI 13 with Android 12, now it's ArrowOS with Android 13.
Before flashing I ended up using ALXR + MonadoVR, this combo rendered full screen, including notch area.
Now that combo doesn't work, and my VR Box broke completely, and I eventually bought "real" headset (Quest 1), so fell free to remove that issue.
