### ISSUE TITLE
[Issue] When lunching steam vr app closes most of the time, when it works black screen and steam vr says device is sleepin

### ISSUE THREAD

**Issue by ernest-cpu** [PhoneVR-Developers/PhoneVR#103]
**Describe the bug/issue**
When lunching steam vr app closes most of the time, when it works black screen and steam vr says device is sleeping. pressing gear button when in vr prompts for me to install google cardboard even though its already installed.

**Local (your) Time when Issue has occured**
1-Jan-2021, 15:30:00 Hrs

**To Reproduce**
Open app
Open steam vr
App closes
re open app
restart steam vr
app closes
sometimes it doesn't close and it goes into the vr mode and the device tracks for a few seconds according to vr view in steam but the screen is black on the phone and then it stops tracking and steamvr says device is sleeping.

**Expected behavior**
I expect that when I open steamvr the app doesnt close and shows me the vr screen and that the screen is not black but shows steamvr and the gear button to work.

**Screenshots**
I can add screen shot if further clarifications is needed.

**Envirnoment (please complete the following information):**
 - Desktop OS: Windows 10 19044.2604
 - Android OS: 12
 - Mobile Device Model Samsung Note10+ and nexus 6P

**Additional context**

**Attached Logs**

[pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/10985721/pvrlog.txt)
[pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/10985723/pvrlog.txt)

**Comment by ernest-cpu** [comment]
[pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/10985722/pvrlog.txt)
phone log

**Comment by ShootingKing-AM** [comment]
Sorry for the late reply, but for `unexpected crashes` you need to attach more logs, as in readme - https://github.com/PhoneVR-Developers/PhoneVR#issue--bug-reporting

the logs you attached give us no clue as to from where issue is stemming from, it looks like normal operation :(
