### ISSUE TITLE
Open XR ?

### ISSUE THREAD

**Issue by UE5Web** [PhoneVR-Developers/PhoneVR#104]
Can I integrate whole code into Unreal Engine 5.1 to use with Open XR API and I don't want to use Steam VR libraries. Can you make it as a feature request ?

**Comment by ShootingKing-AM** [comment]
Yes you can reuse the code subject to [GPL-3.0 license](https://github.com/ShootingKing-AM/PhoneVR/blob/master/LICENSE).
