### ISSUE TITLE
The link in the description to apk file is empty

### ISSUE THREAD

**Issue by danielraziel** [PhoneVR-Developers/PhoneVR#120]
Hi and thanks for all the efforts you've put in this great app. 
1 - I downloaded the master.zip and copied PVRServer insid steamVr's driver folder.
2 - I got stuck here! cuz the link to the Realeses in the description was empty (https://github.com/ShootingKing-AM/PhoneVR/releases/latest)
3 - I found an apk from "Zarik5" but I think it's old and had it's own install.bat etc. and I was confused.

My steamVR doesn't recognize any connection (error 108)
And I maed sure the pairing ports have the same number. both are 33333 on phone and steamVR

is it because of my APK?

**Comment by ShootingKing-AM** [comment]
I recently moved it to a new Organization hence, the links need to be update which I forgot.

You can get the Latest release in this repo home page. https://github.com/PhoneVR-Developers/PhoneVR/issues/120

![image](https://user-images.githubusercontent.com/4137788/234650925-b8187423-2034-4ad5-9c2e-cee639286e1a.png)

**Comment by ShootingKing-AM** [comment]
Please reopen, if its not fixed yet :)
