### ISSUE TITLE
PhoneVR won't work with intranet

### ISSUE THREAD

**Issue by nobeltnium** [PhoneVR-Developers/PhoneVR#217]
**Update:** After fiddling around, i was able to get USB Tethering to work.
![image](https://github.com/PhoneVR-Developers/PhoneVR/assets/70144761/797df493-7b98-450a-9d7f-1bd5cad39aa6)
Once Tethering connection is established, define the **Tethering network** as Private, and printer sharing/discoverable is enabled.
Ping your android device and vice versa to confirm they see each other (my PC and Android can ping each other even though they are public configured by default. But i'm using a non standard windows version)
Put in your clients IP manually, it can now be detected in ALVR.
But still, the client in an Intranet environment will complain about no internet connection :)

Some out of context information:
I have heavily stuttering and artifact on my Android device, in all type of connection like Ethernet, Hotspot, Tethering, Bluetooth tethering, wifi... And find that if i change Adaptive quantization mode to Disable or Temporal, the problem is fixed
![image](https://github.com/PhoneVR-Developers/PhoneVR/assets/70144761/7a73307a-ed87-4450-9179-227a072879b5)

The project states that PhoneVR will work with USB Tethering or Hotspot wifi. But when i open PhoneVR client on my android (connected to the PC via USB Tethering or wifi hotspot). Even though my phone and PC have a sane IP, from the same subnet (192.168.42.xx/24) and can ping each other, My phone will complain that it doesn't have internet connection (which shouldn't matter, since the PC and Phone only need intranet to transfer data). 
FYI:  Wifi/ethernet with internet connection, phoneVR works fine.
Also my windows firewall is down for testing. Confirmed with nc that port 15243, 33333 and 51423 is reachable with netcat
![image](https://github.com/PhoneVR-Developers/PhoneVR/assets/70144761/70792ba6-7f66-407f-a002-21313797073b)
![image](https://github.com/PhoneVR-Developers/PhoneVR/assets/70144761/7bdfc68a-ee2e-4aaf-a288-7490973e01c0)

![image](https://github.com/PhoneVR-Developers/PhoneVR/assets/70144761/22d85b50-e501-43c9-a35c-d6ecd16ba445)

**Comment by ShootingKing-AM** [comment]
Did you read this already ? https://github.com/alvr-org/ALVR/wiki/ALVR-wired-setup-(ALVR-over-USB)

**Comment by nobeltnium** [comment]
Hi ShootingKing-AM, thanks for answering. No i didn't try that (didn't see it in the project home page). I'll try it out and return with an outcome.
In the link  you provided, there is an ADBFowarder that suppose to use for the Quest/Go. Should i need that if i'm on an Android Phone, or it is specifically for the Quest/Go only?

**Comment by ShootingKing-AM** [comment]
ADB is already installed on Android phones, you can try with the default one :)

**Comment by nobeltnium** [comment]
I follow the link you provided but still not able to connect to ALVR on PC through USB cable. 
![image](https://github.com/PhoneVR-Developers/PhoneVR/assets/70144761/ef8dfe90-d3b3-4d7f-94e4-04391de4d19d)
After new client is trusted, I edited clients IP to loop back 127.0.0.1
![image](https://github.com/PhoneVR-Developers/PhoneVR/assets/70144761/45daf0f9-5ed3-438c-8258-27cf848176a2)
But as you can see, in the trustesd clients, it still show the LAN IP. And even though they are connected and streaming, they are using WIFI, not the USB cable. Unplugging the cable will not interrupt streamming.

Also adding client manually doesn't work either.  This is after i plugged my tethered android device in, they just don't see each other
![image](https://github.com/PhoneVR-Developers/PhoneVR/assets/70144761/f15c9a64-35c8-4d41-bdc9-5bf0e75fca69)

![image](https://github.com/PhoneVR-Developers/PhoneVR/assets/70144761/3abb5471-c242-4817-afb9-95f899d64c90)
