### ISSUE TITLE
[Issue/Bug] PhoneVR only produce a single color on Samsung Galaxy S7 / Google Pixel 7

### ISSUE THREAD

**Issue by khoanguyen-3fc** [PhoneVR-Developers/PhoneVR#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this issue has already been addressed in documentation?

- [X] I have read the readme file

### Describe the bug/issue

Screen on mobile only display black or single color, gyro and sound still working

### Local (your) Time when Issue has occurred

2023-10-22 08:04:31

### How To Reproduce your issue

Just use Galaxy S7 as PhoneVR client + ALVR server

### Expected behaviour

VR image should produce

### Screenshots

![Screenshot_20231022-080343_PhoneVR](https://github.com/PhoneVR-Developers/PhoneVR/assets/16377833/78eff4a2-b021-4b4b-9d0e-d110416ff3d7)

### Environment (please complete the following information)

- Desktop OS: Windows 11 22H2
- Android OS: Android 8.0
- Mobile Device Model: Galaxy S7 / SM-G930S
- ALVR Version: v20.2.1
- PhoneVR Version: v1.1.0-beta

### Additional context

PhoneVR on Pixel 7 (Android 14) also have the same behavior, but working on Galaxy Tab S4 (Android 10)

### Attached Logs

[phonevr-s8-logcat.txt](https://github.com/PhoneVR-Developers/PhoneVR/files/13062143/phonevr-s8-logcat.txt)

**Comment by ShootingKing-AM** [comment]
Can you try turning off, foveated rendering in Alvr settings and try again ? Turn off all three options in ALVR -> Settings (restart will be required to settings to take effect)
![image](https://github.com/PhoneVR-Developers/PhoneVR/assets/4137788/15fc8cac-9e2a-4c25-8eaf-96c277af96f7)

**Comment by khoanguyen-3fc** [comment]
I simply disabled 'Foveated rendering,' and it's working as expected. Thank you so much!

**Comment by tutacat** [comment]
duplicate #221 ?

**Comment by ShootingKing-AM** [comment]
This is properly solve in v2.0.0-beta
