### ISSUE TITLE
[Issue/Bug] Decoder error in PhoneVR ALVR client

### ISSUE THREAD

**Issue by 20kdc** [PhoneVR-Developers/PhoneVR#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this issue has already been addressed in documentation?

- [X] I have read the readme file

### Describe the bug/issue

PhoneVR's ALVR client fails due to a decoder error which I am presently unable to understand.

### Local (your) Time when Issue has occurred

11-Dec-2023, 11:30:00 Hrs

### How To Reproduce your issue

Run ALVR v20.2.1 and PhoneVR v1.1.0-beta as indicated by documentation.

### Expected behaviour

Expected behaviour: SteamVR connects and the client does not crash.

### Screenshots

![IMG_20231207_113158](https://github.com/PhoneVR-Developers/PhoneVR/assets/22304167/1dd54f7e-83c0-45b1-b8aa-c9a969b2cae9)

I would absolutely love a better backtrace.

### Environment (please complete the following information)

- Laptop OS: Windows 11 22H2. (I have also seen this error with a Linux host, but I was doing weird stuff (as I was running into even *more* issues on the ALVR/SteamVR side), so that doesn't count.)
- Laptop APU: AMD RENOIRE (AMD Ryzen 7 7730U with Radeon Graphics)
- Android OS: Android 9
- Mobile Device Model: Huawei P30 Lite

### Additional context

Personal ALVR+PhoneVR notes so far:

Linux, ALVR v20.2.1, AppImage, PhoneVR v1.1.0-beta:
 I needed libx264.so.163 **specifically** for the connection to even be made.
 With this, SteamVR gives the error, "Failed to connect to headset display" (496).
 The log contents appear normal (CEncoder listening, Server connected).
 Green streaming indicator for device.

Linux, *ALVR v20.5.0*, AppImage, PhoneVR v1.1.0-beta:
 Same error.

Linux, *ALVR v20.3.1*, *flatpak*, PhoneVR v1.1.0-beta:
 Same error.

*Windows*, *ALVR v20.2.1*, PhoneVR v1.1.0-beta:
 Error in on-device Rust code. I've also seen this error in some of the other configurations I didn't properly record.

*Windows*, *PhoneVR v1.1.0-beta, legacy backend*:
 This actually worked, though with severe caveats.
 These however relate more to my lack of a suitable controller/gamepad for Windows.

Linux, ALVR v20.1.0, AppImage, **PhoneVR v1.0.0-beta**:
 Client actually sent back response messages this time!
 But no errors.
 Green streaming indicator, same SteamVR error as always.

### Attached Logs

The log was added in screenshots. I realize this is not ideal, but I switch OSes when I want to test this versus when I log into my GitHub account.

**Comment by 20kdc** [comment]
I now have more information that may explain why the PhoneVR legacy backend works and ALVR doesn't.

Simply put, when initializing the AMediaCodec, ALVR gives incorrect information, and does not provide maxWidth/maxHeight. https://github.com/alvr-org/ALVR/blob/master/alvr/client_core/src/platform/android/decoder.rs#L177

PhoneVR meanwhile ignores the return value of `AMediaCodec_start` - I do not know if this has a useful effect. https://github.com/PhoneVR-Developers/PhoneVR/blob/6efcea5c9c61ffcf0bd8a3868fcc39a61c4f05b1/code/mobile/android/PhoneVR/app/src/main/cpp/native-lib.cpp#L434

Notably I have also extended my testing to a patched ALVR which only uses Baseline H.264 features. I have attempted to replicate the 512x1024 setup implied by the ALVR code, with no success, but the max-width/max-height keys were not present.

I will need to determine if I can find a way to reliably compile *working* builds of PhoneVR to make the necessary changes to perform further testing.

**Comment by ShootingKing-AM** [comment]
> I now have more information that may explain why the PhoneVR legacy backend works and ALVR doesn't.
> 
> Simply put, when initializing the AMediaCodec, ALVR gives incorrect information, and does not provide maxWidth/maxHeight. https://github.com/alvr-org/ALVR/blob/master/alvr/client_core/src/platform/android/decoder.rs#L177
> 
> PhoneVR meanwhile ignores the return value of `AMediaCodec_start` - I do not know if this has a useful effect.
> 
> https://github.com/PhoneVR-Developers/PhoneVR/blob/6efcea5c9c61ffcf0bd8a3868fcc39a61c4f05b1/code/mobile/android/PhoneVR/app/src/main/cpp/native-lib.cpp#L434
> 
> Notably I have also extended my testing to a patched ALVR which only uses Baseline H.264 features. I have attempted to replicate the 512x1024 setup implied by the ALVR code, with no success, but the max-width/max-height keys were not present.
> 
> I will need to determine if I can find a way to reliably compile _working_ builds of PhoneVR to make the necessary changes to perform further testing.

Interesting finding. Do let me know if you are facing any issue compiling either PhoneVR or ALVR. Also you can start this maxWidth discussion in ALVR/Discord/#dev and ping me if my attention is required.

**Comment by 20kdc** [comment]
While I have still not managed to create a build that works with a *hardware* decoder, I have managed to create a working build of PhoneVR on ALVR master using a *software* decoder, using the commit here: https://github.com/20kdc/ALVR/tree/changeling-buffet-pt-2-upstream-edition

My best guess is that the CSD-0 is simply incorrect or broken in some way. It would be good to figure out a way to share knowledge between Moonlight and ALVR on this issue as it seems that Moonlight have had these sorts of issues handled for a long time.

**Comment by 20kdc** [comment]
In addition to the above, using the ability to specify custom media codec keys in the config, I attempted to patch the width/height/max-width/max-height to be correct. This did not help either, hence my conclusion that the CSD-0 is the culprit.

**Comment by ShootingKing-AM** [comment]
> In addition to the above, using the ability to specify custom media codec keys in the config, I attempted to patch the width/height/max-width/max-height to be correct. This did not help either, hence my conclusion that the CSD-0 is the culprit.

Maybe you can send a PR ALVR quoting this issue ?

**Comment by 20kdc** [comment]
> > In addition to the above, using the ability to specify custom media codec keys in the config, I attempted to patch the width/height/max-width/max-height to be correct. This did not help either, hence my conclusion that the CSD-0 is the culprit.
> 
> Maybe you can send a PR to ALVR quoting this issue ?

While I am not following the exact suggestion, I believe I'm following the sentiment. I've opened PRs targetting software decoder support and if I can figure out a way to make the hardware decoder work, I'll do that too.

**Comment by ShootingKing-AM** [comment]
I think this is solved and can be closed ?

**Comment by 20kdc** [comment]
More or less. If the situation comes up it should now only reduce performance/increase latency, which is not great but it's at least something.
