### ISSUE TITLE
[Issue/Bug]  ALVR v20.2.1 does not work on linux + wayland

### ISSUE THREAD

**Issue by makerio90** [PhoneVR-Developers/PhoneVR#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this issue has already been addressed in documentation?

- [X] I have read the readme file

### Describe the bug/issue

ALVR v20.2.1[crashes instantly on startub](https://github.com/alvr-org/ALVR/issues/1896) on Wayland. trying to build from source causes build errors (see same issue). the latest commit builds + runs fine, but PhonVR wont connect due to the version mismatch

### Local (your) Time when Issue has occurred

Thu Dec  7 06:17:13 PM EST 2023

### How To Reproduce your issue

1. run a linux system with wayland
2. install and run wayland alvr v20.2.1

### Expected behaviour

alvr should start running normaly

### Environment (please complete the following information)

 - Desktop Os: Arch linux, hyprland
 - android os version: 11
 - android device model: pixel 6

**Comment by ShootingKing-AM** [comment]
This is a ALVR issue/bug, should be opened on ALVR repo, and the latest version should fix this. If you want some building help, do state the issues, Thanks !
