### ISSUE TITLE
[Feature Request] RGB spectrum correction

### ISSUE THREAD

**Issue by loikki** [PhoneVR-Developers/PhoneVR#276]
Hi,

My screen is far too red when playing / looking at movie. Could it be possible to add a RGB spectrum correction option?

For reference, you can look at the issue I have opened in ALVR https://github.com/alvr-org/ALVR/issues/1914#issuecomment-1837226719

Thanks for your help and time,
Best

**Comment by ShootingKing-AM** [comment]
This has to be implemented on ALVR end, either on server of Client. If you ask me, the option has to be implemented on Server end, any more processing on Client end will just increase already loaded client decoding work. As we already know the latency contribution of client is like ~75% of total latency, which is bad, we need to work towards deloading client.

In any way, Client or server the code is on the ALVR repo. You need to keep the issue open on ALVR repo, i will make a PR if i get some time.

**Comment by loikki** [comment]
Thanks for your answer. I will see with ALVR then
