### ISSUE TITLE
PhoneVC crashes on startup on an HTC Vive Focus Pro

### ISSUE THREAD

**Issue by benpocalypse** [PhoneVR-Developers/PhoneVR#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this issue has already been addressed in documentation?

- [X] I have read the readme file

### Describe the bug/issue

I loaded the APK onto my HTC Vive Focus Plus (which I recently got at a deep discount) and when I attempt to open the app, it crashes with a partial stacktrace visible. I was able to take a screenshot of the actual error and will attach it to this ticket.

I know it's a long shot as to fixing this, but thought I would bring it up in case it's a solvable issue. I'm not even sure what version of Android the Vive Focus Plus is running, as they've obfuscated the Android version numbering with their own SDK versions. I would look into it myself by I don't have the Android SDK or related tooling installed, and haven't worked on Android in close to a decade.

![Screenshot_20240131_175303](https://github.com/PhoneVR-Developers/PhoneVR/assets/6274196/239d3a7b-8839-433a-b5ea-05c1ee24dbe7)

### Local (your) Time when Issue has occurred

Wednesday, January 31, 7:48PM EST.

### How To Reproduce your issue

1. Load the PhoneVR APK onto the Vive Focus Plus.
2. Attempt to launch the PhoneVR app.
3. Witness the crash screen.

### Expected behaviour

I would hope this would run on the Vive Focus Plus, because it also runs Android.

### Screenshots

Attached above.

### Environment (please complete the following information)

Desktop OS: elementary OS 7.1
Headset OS: Android...unknown version

**Comment by ShootingKing-AM** [comment]
What's the use case of PhoneVR for HTC vive pro? Also the Imagereader_newWithUsage is a known compatibility issue. Seems HTC vive pro has lower than required Android SDK.

**Comment by benpocalypse** [comment]
The HTC Vive Focus Plus is only my 2nd foray into VR, the previous being the now dead Google Daydream headset. The Focus Plus is a standalone, WiFi only, headset that has a very limited built in app store. I was hoping that I could make use of PhoneVR to allow me to play games via SteamVR. The Android ALVR Apk doesn't even install on the headset, as it complains that the package isn't readable.

If the Android version is too low to support this, feel free to close this ticket. I just thought maybe it was worth a shot.

**Comment by ShootingKing-AM** [comment]
It seems vive focus plus has Android level 7.1, ALVR requires 8+ devices (which can be developed to support lower version)

You can try setting up the legacy version of PhoneVR for now. That should work but the latest development is taking place on PhoneVR- with alvr server.

This issue is same as https://github.com/PhoneVR-Developers/PhoneVR/issues/157, hence closing this thread, you can follow the original thread.

Do consider donating some coffee to get more devs motivated to solve the issue ☕

**Comment by benpocalypse** [comment]
Thank you so much. I'm kind of blown away that a headset released in 2019 is running an Android version from 2016. Coffee will be incoming - thank you.
