### ISSUE TITLE
Latency issues

### ISSUE THREAD

**Issue by gammaMgames** [PhoneVR-Developers/PhoneVR#44]
I’m having Extreme latency issues and I’m 5ghz wifi and all the settings are default I wheb I change them it gets worse here is a video 
https://youtu.be/A8TD9B2qHxs

**Comment by ShootingKing-AM** [comment]
The mobile components seems to be lagging behind for rendering the frame, which might be causing the issue. As discussed on discord, the Top row, Mobile componenets viz., Network Stream Receiver FPS, Media Decoder FPS, OpenGL Renderer FPS are acting like then have been capped to `30 FPS` when the config is at `60 FPS`. Will be working on the issue, Thanks for reporting.

**Comment by ShootingKing-AM** [comment]
@gammaMgames Can you try the latest build and use tethering and see if there is any improvement ?

**Comment by u-Kotovsky** [comment]
I have same problem with 2.4Ghz Wifi, is it possible to implement other encoders?

**Comment by ShootingKing-AM** [comment]
> I have same problem with 2.4Ghz Wifi, is it possible to implement other encoders?

Yup, WIP in https://github.com/PhoneVR-Developers/PhoneVR/pull/54

**Comment by ShootingKing-AM** [comment]
This has been solved in latest release by using ALVR Server. If its not feel free to reopen the issue.
