### ISSUE TITLE
Hardware encoding support

### ISSUE THREAD

**Issue by fragmental** [PhoneVR-Developers/PhoneVR#52]
I noticed that PhoneVR uses x264 encoding, is support for gpu Hardware encoding such as NVENC, Quick Sync, or VCE planned?

**Comment by ShootingKing-AM** [comment]
Hi,
Yes PVR is using libx264 till now. and Yes Hardware encoding via FFMPEG is on todo, FFMPEG supports NVENC and other common hardware encoders.

**Comment by fragmental** [comment]
I see.  Thanks for the quick response.

**Comment by ShootingKing-AM** [comment]
This has been solved in latest release by using ALVR Server. If its not feel free to reopen the issue.
