### ISSUE TITLE
PhoneVr stuck at black screen

### ISSUE THREAD

**Issue by Sentokaio-Studios** [PhoneVR-Developers/PhoneVR#55]
I have an issue in PhoneVR. Everything goes normally as it should be. But when i connect to the game. ig get stuck into a black screen. The game works fine, but in the cellphone, it just shows a black screen

**Comment by ShootingKing-AM** [comment]
Can you attach logs Please.

**Comment by laluv193** [comment]
`PVR SERVER LOG HERE -->

12:18:13(253) - 05.01.2021 -- 13 max  ------------------------------------
12:18:13(253) - 05.01.2021 -- 13 001  Getting server
12:18:13(254) - 05.01.2021 -- 13 000  [ServerProvider::Init] Initializing server
12:18:13(255) - 05.01.2021 -- 13 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:18:13(521) - 05.01.2021 -- 13 265  [ServerProvider::Init::PVRStartConnectionListener] recvd PAIR_HMD Msg from ip: 192.168.1.101
12:18:13(521) - 05.01.2021 -- 13 001  [TCPTalker::TCPTalker] Init'ed with p:33333 isServer:0 ip:192.168.1.101
12:18:13(522) - 05.01.2021 -- 13 002  [TCPTalker::TCPTalker] Talker is Client and Connecting to ip:192.168.1.101 & port:33333...
12:18:28(896) - 05.01.2021 -- 28 max  [TCPTalker::TCPTalker] Talker is Connected. Trying to read some data...
12:18:28(899) - 05.01.2021 -- 28 002  HMD initializing
12:18:29(085) - 05.01.2021 -- 29 187  HMD initialized
12:18:29(099) - 05.01.2021 -- 29 014  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
12:18:30(047) - 05.01.2021 -- 30 947  [HMD::talker]: addData msg RCV'ed....
12:18:30(047) - 05.01.2021 -- 30 001  [HMD::talker]: addData: Viewport:  left: -1.399369  top: 1.520426  right: 1.626278  bottom: -1.475492
12:18:30(048) - 05.01.2021 -- 30 000  [HMD::talker]: IPD: 0.063000
12:19:04(622) - 05.01.2021 -- 04 max  ------------------------------------
12:19:04(623) - 05.01.2021 -- 04 001  Getting server
12:19:04(623) - 05.01.2021 -- 04 000  [ServerProvider::Init] Initializing server
12:19:04(624) - 05.01.2021 -- 04 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:19:09(624) - 05.01.2021 -- 09 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
12:19:09(988) - 05.01.2021 -- 09 max  ------------------------------------
12:19:09(988) - 05.01.2021 -- 09 000  Getting server
12:19:09(989) - 05.01.2021 -- 09 000  [ServerProvider::Init] Initializing server
12:19:09(994) - 05.01.2021 -- 09 005  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:19:14(998) - 05.01.2021 -- 14 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
12:19:18(290) - 05.01.2021 -- 18 max  ------------------------------------
12:19:18(291) - 05.01.2021 -- 18 000  Getting server
12:19:18(291) - 05.01.2021 -- 18 001  [ServerProvider::Init] Initializing server
12:19:18(292) - 05.01.2021 -- 18 001  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:19:23(292) - 05.01.2021 -- 23 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
12:19:23(613) - 05.01.2021 -- 23 max  ------------------------------------
12:19:23(613) - 05.01.2021 -- 23 000  Getting server
12:19:23(613) - 05.01.2021 -- 23 001  [ServerProvider::Init] Initializing server
12:19:23(618) - 05.01.2021 -- 23 005  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:19:28(618) - 05.01.2021 -- 28 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
12:20:49(526) - 05.01.2021 -- 49 max  ------------------------------------
12:20:49(526) - 05.01.2021 -- 49 000  Getting server
12:20:49(527) - 05.01.2021 -- 49 001  [ServerProvider::Init] Initializing server
12:20:49(528) - 05.01.2021 -- 49 001  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:20:49(833) - 05.01.2021 -- 49 306  [ServerProvider::Init::PVRStartConnectionListener] recvd PAIR_HMD Msg from ip: 192.168.1.101
12:20:49(834) - 05.01.2021 -- 49 000  [TCPTalker::TCPTalker] Init'ed with p:33333 isServer:0 ip:192.168.1.101
12:20:49(836) - 05.01.2021 -- 49 002  [TCPTalker::TCPTalker] Talker is Client and Connecting to ip:192.168.1.101 & port:33333...
12:20:50(027) - 05.01.2021 -- 50 190  [TCPTalker::TCPTalker] Talker is Connected. Trying to read some data...
12:20:50(029) - 05.01.2021 -- 50 002  HMD initializing
12:20:50(215) - 05.01.2021 -- 50 187  HMD initialized
12:20:50(216) - 05.01.2021 -- 50 001  [ServerProvider::Init] Server initialized
12:20:50(217) - 05.01.2021 -- 50 001  [Activating HMD]... Setting Props
12:20:50(218) - 05.01.2021 -- 50 001  [Activating HMD]: waiting for additionalData from Client...
12:20:51(160) - 05.01.2021 -- 51 941  [HMD::talker]: addData msg RCV'ed....
12:20:51(160) - 05.01.2021 -- 51 000  [HMD::talker]: addData: Viewport:  left: -1.399369  top: 1.520426  right: 1.626278  bottom: -1.475492
12:20:51(160) - 05.01.2021 -- 51 001  [HMD::talker]: IPD: 0.063000
12:20:51(161) - 05.01.2021 -- 51 000  [Activating HMD]: Rcvd addotionalData... Starting PVRStartStreamer with [WxH]:1704x960
12:20:51(161) - 05.01.2021 -- 51 001  [PVRStartReceiveData] UDP receive started
12:20:51(162) - 05.01.2021 -- 51 000  [Activating HMD]: HMD activated with id: 0
12:20:51(162) - 05.01.2021 -- 51 000  Using default setting value: encoder.rc_method = 1
12:20:51(162) - 05.01.2021 -- 51 001  [Open VR GetWindowBounds] Returning w 0 h 0
12:20:51(163) - 05.01.2021 -- 51 000  Using default setting value: encoder.qcomp = 0.000000
12:20:51(163) - 05.01.2021 -- 51 000  [Open VR GetRecommendedRenderTargetSize] Returning w 0 h 0
12:20:51(163) - 05.01.2021 -- 51 001  Using default setting value: encoder.bitrate = -1
12:20:51(164) - 05.01.2021 -- 51 000  Using default setting value: encoder.keyint_max = -1
12:20:51(164) - 05.01.2021 -- 51 001  Using default setting value: encoder.intra_refresh = 0
12:24:08(131) - 05.01.2021 -- 08 max  Server enter standby
12:24:09(040) - 05.01.2021 -- 09 909  HMD deactivating
12:24:09(040) - 05.01.2021 -- 09 000  Closing data thread
12:24:09(041) - 05.01.2021 -- 09 001  UDP receive stopped
12:24:09(042) - 05.01.2021 -- 09 001  Closing video thread
12:34:37(134) - 05.01.2021 -- 37 max  ------------------------------------
12:34:37(134) - 05.01.2021 -- 37 001  Getting server
12:34:37(135) - 05.01.2021 -- 37 000  [ServerProvider::Init] Initializing server
12:34:37(136) - 05.01.2021 -- 37 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:34:42(136) - 05.01.2021 -- 42 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
12:34:42(462) - 05.01.2021 -- 42 max  ------------------------------------
12:34:42(462) - 05.01.2021 -- 42 001  Getting server
12:34:42(462) - 05.01.2021 -- 42 000  [ServerProvider::Init] Initializing server
12:34:42(468) - 05.01.2021 -- 42 005  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:34:47(468) - 05.01.2021 -- 47 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
12:34:53(466) - 05.01.2021 -- 53 max  ------------------------------------
12:34:53(466) - 05.01.2021 -- 53 000  Getting server
12:34:53(467) - 05.01.2021 -- 53 001  [ServerProvider::Init] Initializing server
12:34:53(468) - 05.01.2021 -- 53 001  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:34:58(469) - 05.01.2021 -- 58 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
12:34:58(844) - 05.01.2021 -- 58 max  ------------------------------------
12:34:58(844) - 05.01.2021 -- 58 001  Getting server
12:34:58(845) - 05.01.2021 -- 58 000  [ServerProvider::Init] Initializing server
12:34:58(851) - 05.01.2021 -- 58 007  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:35:03(852) - 05.01.2021 -- 03 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
12:35:09(692) - 05.01.2021 -- 09 max  ------------------------------------
12:35:09(692) - 05.01.2021 -- 09 000  Getting server
12:35:09(693) - 05.01.2021 -- 09 000  [ServerProvider::Init] Initializing server
12:35:09(694) - 05.01.2021 -- 09 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:35:14(695) - 05.01.2021 -- 14 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
12:35:15(057) - 05.01.2021 -- 15 max  ------------------------------------
12:35:15(057) - 05.01.2021 -- 15 000  Getting server
12:35:15(058) - 05.01.2021 -- 15 001  [ServerProvider::Init] Initializing server
12:35:15(065) - 05.01.2021 -- 15 007  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:35:20(065) - 05.01.2021 -- 20 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
12:35:23(526) - 05.01.2021 -- 23 max  ------------------------------------
12:35:23(526) - 05.01.2021 -- 23 000  Getting server
12:35:23(526) - 05.01.2021 -- 23 001  [ServerProvider::Init] Initializing server
12:35:23(529) - 05.01.2021 -- 23 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:35:28(529) - 05.01.2021 -- 28 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
12:35:28(924) - 05.01.2021 -- 28 max  ------------------------------------
12:35:28(924) - 05.01.2021 -- 28 001  Getting server
12:35:28(924) - 05.01.2021 -- 28 000  [ServerProvider::Init] Initializing server
12:35:28(930) - 05.01.2021 -- 28 006  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
12:35:33(931) - 05.01.2021 -- 33 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
13:57:04(530) - 05.01.2021 -- 04 max  ------------------------------------
13:57:04(531) - 05.01.2021 -- 04 001  Getting server
13:57:04(532) - 05.01.2021 -- 04 000  [ServerProvider::Init] Initializing server
13:57:04(533) - 05.01.2021 -- 04 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
13:57:09(534) - 05.01.2021 -- 09 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
13:57:10(028) - 05.01.2021 -- 10 max  ------------------------------------
13:57:10(028) - 05.01.2021 -- 10 000  Getting server
13:57:10(028) - 05.01.2021 -- 10 001  [ServerProvider::Init] Initializing server
13:57:10(033) - 05.01.2021 -- 10 004  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
13:57:15(038) - 05.01.2021 -- 15 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
13:57:21(163) - 05.01.2021 -- 21 max  ------------------------------------
13:57:21(164) - 05.01.2021 -- 21 000  Getting server
13:57:21(164) - 05.01.2021 -- 21 000  [ServerProvider::Init] Initializing server
13:57:21(166) - 05.01.2021 -- 21 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
13:57:26(168) - 05.01.2021 -- 26 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
13:57:26(533) - 05.01.2021 -- 26 max  ------------------------------------
13:57:26(534) - 05.01.2021 -- 26 001  Getting server
13:57:26(534) - 05.01.2021 -- 26 000  [ServerProvider::Init] Initializing server
13:57:26(540) - 05.01.2021 -- 26 005  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
13:57:31(540) - 05.01.2021 -- 31 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
16:22:04(792) - 05.01.2021 -- 04 max  ------------------------------------
16:22:04(794) - 05.01.2021 -- 04 002  Getting server
16:22:04(794) - 05.01.2021 -- 04 000  [ServerProvider::Init] Initializing server
16:22:04(796) - 05.01.2021 -- 04 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
16:22:09(795) - 05.01.2021 -- 09 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
16:22:10(384) - 05.01.2021 -- 10 max  ------------------------------------
16:22:10(384) - 05.01.2021 -- 10 001  Getting server
16:22:10(384) - 05.01.2021 -- 10 000  [ServerProvider::Init] Initializing server
16:22:10(396) - 05.01.2021 -- 10 012  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
16:22:15(401) - 05.01.2021 -- 15 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
16:22:21(816) - 05.01.2021 -- 21 max  ------------------------------------
16:22:21(817) - 05.01.2021 -- 21 000  Getting server
16:22:21(817) - 05.01.2021 -- 21 001  [ServerProvider::Init] Initializing server
16:22:21(819) - 05.01.2021 -- 21 001  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
16:22:26(819) - 05.01.2021 -- 26 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
16:22:27(167) - 05.01.2021 -- 27 max  ------------------------------------
16:22:27(168) - 05.01.2021 -- 27 001  Getting server
16:22:27(168) - 05.01.2021 -- 27 000  [ServerProvider::Init] Initializing server
16:22:27(173) - 05.01.2021 -- 27 004  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
16:22:32(173) - 05.01.2021 -- 32 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
18:38:10(405) - 05.01.2021 -- 10 max  ------------------------------------
18:38:10(408) - 05.01.2021 -- 10 003  Getting server
18:38:10(409) - 05.01.2021 -- 10 000  [ServerProvider::Init] Initializing server
18:38:10(410) - 05.01.2021 -- 10 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
18:38:15(411) - 05.01.2021 -- 15 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
18:38:16(369) - 05.01.2021 -- 16 max  ------------------------------------
18:38:16(370) - 05.01.2021 -- 16 001  Getting server
18:38:16(370) - 05.01.2021 -- 16 000  [ServerProvider::Init] Initializing server
18:38:16(372) - 05.01.2021 -- 16 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
18:38:21(372) - 05.01.2021 -- 21 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
18:45:24(145) - 05.01.2021 -- 24 max  ------------------------------------
18:45:24(147) - 05.01.2021 -- 24 002  Getting server
18:45:24(148) - 05.01.2021 -- 24 000  [ServerProvider::Init] Initializing server
18:45:24(150) - 05.01.2021 -- 24 003  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
18:45:24(174) - 05.01.2021 -- 24 023  [ServerProvider::Init::PVRStartConnectionListener] recvd PAIR_HMD Msg from ip: 192.168.1.101
18:45:24(175) - 05.01.2021 -- 24 002  [TCPTalker::TCPTalker] Init'ed with p:33333 isServer:0 ip:192.168.1.101
18:45:24(177) - 05.01.2021 -- 24 002  [TCPTalker::TCPTalker] Talker is Client and Connecting to ip:192.168.1.101 & port:33333...
18:45:45(323) - 05.01.2021 -- 45 max  HMD initializing
 error: Uma tentativa de conexão falhou porque o componente conectado não respondeu

corretamente após um período de tempo ou a conexão estabelecida falhou

porque o host conectado não respondeu.
18:45:45(555) - 05.01.2021 -- 45 232  HMD initialized
18:45:45(572) - 05.01.2021 -- 45 018  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
18:46:50(195) - 05.01.2021 -- 50 max  ------------------------------------
18:46:50(196) - 05.01.2021 -- 50 001  Getting server
18:46:50(197) - 05.01.2021 -- 50 001  [ServerProvider::Init] Initializing server
18:46:50(200) - 05.01.2021 -- 50 003  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
18:46:55(200) - 05.01.2021 -- 55 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
18:46:55(991) - 05.01.2021 -- 55 max  ------------------------------------
18:46:55(993) - 05.01.2021 -- 55 001  Getting server
18:46:55(994) - 05.01.2021 -- 55 001  [ServerProvider::Init] Initializing server
18:46:55(997) - 05.01.2021 -- 55 003  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
18:47:00(996) - 05.01.2021 -- 00 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
19:34:24(613) - 05.01.2021 -- 24 max  ------------------------------------
19:34:24(615) - 05.01.2021 -- 24 002  Getting server
19:34:24(617) - 05.01.2021 -- 24 001  [ServerProvider::Init] Initializing server
19:34:24(618) - 05.01.2021 -- 24 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
19:34:29(618) - 05.01.2021 -- 29 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
19:34:30(008) - 05.01.2021 -- 30 max  ------------------------------------
19:34:30(010) - 05.01.2021 -- 30 002  Getting server
19:34:30(023) - 05.01.2021 -- 30 013  [ServerProvider::Init] Initializing server
19:34:30(025) - 05.01.2021 -- 30 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
19:34:35(026) - 05.01.2021 -- 35 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
19:34:38(570) - 05.01.2021 -- 38 max  ------------------------------------
19:34:38(572) - 05.01.2021 -- 38 001  Getting server
19:34:38(572) - 05.01.2021 -- 38 001  [ServerProvider::Init] Initializing server
19:34:38(575) - 05.01.2021 -- 38 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
19:34:43(575) - 05.01.2021 -- 43 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
19:34:43(913) - 05.01.2021 -- 43 max  ------------------------------------
19:34:43(914) - 05.01.2021 -- 43 001  Getting server
19:34:43(916) - 05.01.2021 -- 43 001  [ServerProvider::Init] Initializing server
19:34:43(919) - 05.01.2021 -- 43 004  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
19:34:48(919) - 05.01.2021 -- 48 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
19:35:34(782) - 05.01.2021 -- 34 max  ------------------------------------
19:35:34(784) - 05.01.2021 -- 34 001  Getting server
19:35:34(785) - 05.01.2021 -- 34 002  [ServerProvider::Init] Initializing server
19:35:34(787) - 05.01.2021 -- 34 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
19:35:39(788) - 05.01.2021 -- 39 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
19:35:40(150) - 05.01.2021 -- 40 max  ------------------------------------
19:35:40(151) - 05.01.2021 -- 40 001  Getting server
19:35:40(152) - 05.01.2021 -- 40 001  [ServerProvider::Init] Initializing server
19:35:40(157) - 05.01.2021 -- 40 004  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
19:35:45(156) - 05.01.2021 -- 45 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
19:35:48(520) - 05.01.2021 -- 48 max  ------------------------------------
19:35:48(521) - 05.01.2021 -- 48 001  Getting server
19:35:48(522) - 05.01.2021 -- 48 001  [ServerProvider::Init] Initializing server
19:35:48(524) - 05.01.2021 -- 48 003  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
19:35:53(524) - 05.01.2021 -- 53 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
19:35:53(871) - 05.01.2021 -- 53 max  ------------------------------------
19:35:53(872) - 05.01.2021 -- 53 001  Getting server
19:35:53(874) - 05.01.2021 -- 53 002  [ServerProvider::Init] Initializing server
19:35:53(877) - 05.01.2021 -- 53 003  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
19:35:58(878) - 05.01.2021 -- 58 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
19:36:28(671) - 05.01.2021 -- 28 max  ------------------------------------
19:36:28(674) - 05.01.2021 -- 28 003  Getting server
19:36:28(674) - 05.01.2021 -- 28 000  [ServerProvider::Init] Initializing server
19:36:28(677) - 05.01.2021 -- 28 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
19:36:33(677) - 05.01.2021 -- 33 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
19:39:43(351) - 05.01.2021 -- 43 max  ------------------------------------
19:39:43(352) - 05.01.2021 -- 43 000  Getting server
19:39:43(354) - 05.01.2021 -- 43 003  [ServerProvider::Init] Initializing server
19:39:43(359) - 05.01.2021 -- 43 011  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
19:39:48(359) - 05.01.2021 -- 48 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
19:43:03(577) - 05.01.2021 -- 03 max  ------------------------------------
19:43:03(579) - 05.01.2021 -- 03 001  Getting server
19:43:03(579) - 05.01.2021 -- 03 000  [ServerProvider::Init] Initializing server
19:43:03(580) - 05.01.2021 -- 03 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
19:43:08(581) - 05.01.2021 -- 08 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
19:50:18(126) - 05.01.2021 -- 18 max  ------------------------------------
19:50:18(126) - 05.01.2021 -- 18 000  Getting server
19:50:18(127) - 05.01.2021 -- 18 000  [ServerProvider::Init] Initializing server
19:50:18(129) - 05.01.2021 -- 18 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
19:50:23(129) - 05.01.2021 -- 23 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
20:08:05(525) - 05.01.2021 -- 05 max  ------------------------------------
20:08:05(525) - 05.01.2021 -- 05 000  Getting server
20:08:05(525) - 05.01.2021 -- 05 000  [ServerProvider::Init] Initializing server
20:08:05(526) - 05.01.2021 -- 05 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
20:08:10(526) - 05.01.2021 -- 10 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
15:09:10(759) - 07.01.2021 -- 10 max  ------------------------------------
15:09:10(763) - 07.01.2021 -- 10 003  Getting server
15:09:10(763) - 07.01.2021 -- 10 000  [ServerProvider::Init] Initializing server
15:09:10(765) - 07.01.2021 -- 10 002  [PVRSockets::PVRStartConnectionListener] Listener Started on Port : 33333
15:09:10(771) - 07.01.2021 -- 10 006  [ServerProvider::Init::PVRStartConnectionListener] recvd PAIR_HMD Msg from ip: 192.168.1.101
15:09:10(772) - 07.01.2021 -- 10 000  [TCPTalker::TCPTalker] Init'ed with p:33333 isServer:0 ip:192.168.1.101
15:09:10(775) - 07.01.2021 -- 10 003  [TCPTalker::TCPTalker] Talker is Client and Connecting to ip:192.168.1.101 & port:33333...
15:09:10(795) - 07.01.2021 -- 10 020  [TCPTalker::TCPTalker] Talker is Connected. Trying to read some data...
15:09:10(796) - 07.01.2021 -- 10 001  HMD initializing
15:09:10(862) - 07.01.2021 -- 10 066  HMD initialized
15:09:10(862) - 07.01.2021 -- 10 001  [ServerProvider::Init::PVRStartConnectionListener] Error: could not activate HMD
15:09:11(667) - 07.01.2021 -- 11 805  [HMD::talker]: addData msg RCV'ed....
15:09:11(668) - 07.01.2021 -- 11 001  [HMD::talker]: addData: Viewport:  left: -1.399369  top: 1.520426  right: 1.626278  bottom: -1.475492
15:09:11(668) - 07.01.2021 -- 11 000  [HMD::talker]: IPD: 0.063000
15:09:15(764) - 07.01.2021 -- 15 max  [ServerProvider::Init] Pairing failed! Cause: timeout ... for 5secs
`

**Comment by ShootingKing-AM** [comment]
You need to attach the the Mobile logs also as requested in [Readme](https://github.com/ShootingKing-AM/PhoneVR#issue--bug-reporting). Thanks !

**Comment by Tyberkid967** [comment]
I am also having the same issue so here is the log from my phone
[pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5928990/pvrlog.txt)

**Comment by ShootingKing-AM** [comment]
> I am also having the same issue so here is the log from my phone
> [pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5928990/pvrlog.txt)

Which version of windows, android are you using ? Is it Android 11 ? What's the android device model and brand?

Thanks for the logs.

**Comment by Tyberkid967** [comment]
I am using Windows 10 and I have a Revvl 4+ from T-Mobile running Android 10

**Comment by ShootingKing-AM** [comment]
Should be fixed in latest PhoneVR
