### ISSUE TITLE
[Feature] Will there be an option to connect PhoneVR to StreamVR using USB cable?

### ISSUE THREAD

**Issue by Looooong** [PhoneVR-Developers/PhoneVR#79]
Even when connecting over 5GHz wifi, I experence lag and the android app would freeze after few seconds after connecting to StreamVR. I tested VRidge using USB cable before and it was really reponsive. So I wonder if there will be an option to connect PhoneVR to StreamVR using the USB cable?

**Comment by ShootingKing-AM** [comment]
Hi,
Its already there, you need to use USB Tethering Option.

**Comment by Looooong** [comment]
I couldn't connect to SteamVR using USB Tethering. Is there any requirement or configuration to enable this option?

**Comment by ckasarda** [comment]
I am wondering about this too because it just does not work on wifi anymore. Also, I don't see an option to select usb tethering either. I think it only has wifi as a means of connecting. I am trying to see if maybe I can fork this and write my own solution or find a solution elsewhere.

**Comment by ShootingKing-AM** [comment]
Yes @pacjo has answered the question, you just need to enable usb tethering on Phone and PhoneVR will automatically select it. If its not solved yet, please re-open with logs :)
