### ISSUE TITLE
[Bug] Crush on android when i start SteamVR

### ISSUE THREAD

**Issue by ghost** [PhoneVR-Developers/PhoneVR#80]
![Screenshot_20210724-213630_PhoneVR](https://user-images.githubusercontent.com/64200268/126977462-872ee2e9-3a86-464a-a0bd-0683d40ab9b7.png)

**Comment by ShootingKing-AM** [comment]
Thanks for trying out PVR. Please attach all relavent logs - https://github.com/ShootingKing-AM/PhoneVR#issue--bug-reporting

**Comment by ShootingKing-AM** [comment]
This should be fixed in latest version of PhoneVR+ALVR
