### ISSUE TITLE
Random disconnecting when in VR.

### ISSUE THREAD

**Issue by Mineplayerminer** [PhoneVR-Developers/PhoneVR#83]
When Im playing in VR, sometimes, the app throws me back to the menu for finding the network. Would it be possible to make this app communicate through the USB cable? I also found a big latency even when Im on a 5G Wifi (300Mbps)

**Comment by IvanGorinich-GitHub** [comment]
How you connect PVR to SteamVR

**Comment by pehage** [comment]
You can actually do it with Ethernet over USB tethering. Technically, it is still over internet, but it goes way faster, as long as your got USB 3 on your phone... (and a USB e cable) 
This works for Android, I don't know how it goes for Iphone, but with Android, the setting is under development settings.

**Comment by ShootingKing-AM** [comment]
Thanks for trying out PVR. Please attach all relavent logs - https://github.com/ShootingKing-AM/PhoneVR#issue--bug-reporting
