### ISSUE TITLE
Unnable to change the VR Headset preset, even with the Carboard app installed

### ISSUE THREAD

**Issue by Katzenwerfer** [PhoneVR-Developers/PhoneVR#86]
I'm unable to change the preset as it asks me to install the Carboard app even though I already have it installed (the title is pretty self-explanatory)

**Comment by ShootingKing-AM** [comment]
What preset do you mean exactly ? If you can explain with screenshots, it would be much easier.

**Comment by Mineplayerminer** [comment]
> What preset do you mean exactly ? If you can explain with screenshots, it would be much easier.

I think he meant that QR Code the headsets have on them to set the configs. (Lens size, IPD, and others...)

**Comment by ShootingKing-AM** [comment]
This has been solved in latest release by using ALVR-Cardboard option on PhoneVR app. If its not feel free to reopen the issue.
