### ISSUE TITLE
[suggestion] better installer, like other apps

### ISSUE THREAD

**Issue by atesin** [PhoneVR-Developers/PhoneVR#87]
hi...  i was testing another vr-phone app = irun vr

it functions similar to this in the sense you use your phone as vr visor, install a software/steamrv-plugin (as msi file)...  then connects with phone each other through network (using mdns i guess)

what came my attention is installation for steamvr is so straightforward and seamless ... you install the msi and the software just appear inside steamvr by itself...  and it launches and place an icon in system tray automatically, and steamvr recognizes it at once, all without user intervention

![image](https://user-images.githubusercontent.com/8086106/148886351-9b809160-6083-498a-97d8-f84ea91df91f.png)

do you know how they do it?? .. try it, maybe you will get some ideas

**Comment by ShootingKing-AM** [comment]
This has been solved in latest release.
