### ISSUE TITLE
Is this application still working?

### ISSUE THREAD

**Issue by user6304** [PhoneVR-Developers/PhoneVR#88]
Last release more than a year ago...
I might try if it does tomorrow or sometime next week, but if anyone knows if it actually still works, I'd be happy to know

**Comment by Lelaxlp** [comment]
Yep, didn't hook up any controllers or anything yet, but game startet just fine and instantly found device!
So yes, does still work.
Will continue setting stuff up tomorrow

**Comment by Fancy2209** [comment]
It does work here too
Tested on a friend PC because I wanted to show him Vivecraft

**Comment by ShootingKing-AM** [comment]
> Yep, didn't hook up any controllers or anything yet, but game startet just fine and instantly found device! So yes, does still work. Will continue setting stuff up tomorrow

This is made by gods ! Cannot be not-working ever XD

**Comment by Lelaxlp** [comment]
You may want to state that this is still working in the readme.md, as I almost chose to try the uncontinued AVRI-Fork for GearVR instead of this masterful application :)

**Comment by Mineplayerminer** [comment]
Does not longer work for me, it says that the SteamVR has crashed recently and following addons were blocked including the **PVRServer**

**Comment by BitBlitObviMormon** [comment]
> You may want to state that this is still working in the readme.md, as I almost chose to try the uncontinued AVRI-Fork for GearVR instead of this masterful application :)

What's the point of declaring that it still works in a readme? Isn't any actively supported software supposed to work? (Though I guess "active" is up for debate...)

Even then, it's kind of hard to say it simply works without a large testing base. Developing for hundreds of different phone models is hard and, like in my case, it doesn't work for every phone. (#92) I say just try out the different kits and see if they work or don't. I'd be happy just to have working VR that doesn't cost me money. 😁

**Comment by Mineplayerminer** [comment]
I mean, even on a custom ROM without any Xiaomi crap, I still have the cropped and shifted image next to my notch.
