### ISSUE TITLE
[Issue] video on phone is too blurry

### ISSUE THREAD

**Issue by eleven-monkey** [PhoneVR-Developers/PhoneVR#90]
It still works and easy to install.the only problem to me is the video on Phone is too blurry。how can I set it to
 a higher resolution？
![image](https://user-images.githubusercontent.com/62041627/169657057-21b4596a-b9a5-4655-b74b-4b073578f66d.png)
![image](https://user-images.githubusercontent.com/62041627/169657076-1e3ad5fd-22bd-41e7-9e6a-be142f3e0327.png)
I tried vridge，the video of that app is clear。

**Comment by weclont** [comment]
I have the same problem, adjusting the `C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\PVRServer\pursettings.json` file has no actual effect on the resolution, but higher settings increase the delay; Adjusting in steamVR also had no effect. How can this be resolved?

**Comment by JustWhoOk** [comment]
I wonder that also, so far I find out pvr using high fov and zoom it in the phone, but vridge seem using normal fov 
![vridge](https://user-images.githubuserconte
![pvr](https://user-images.githubusercontent.com/115952329/230786077-ab00fed3-7d2b-4856-a553-4924de5a5b33.png)
nt.com/115952329/230786064-4b3d36fa-5c7e-47cf-abc7-3f237dcd69d1.png)
![pvr](https://user-images.githubusercontent.com/115952329/230786067-60201a28-45c3-4d1d-b107-582164149a8b.png)
and try to capture them to stream on phone, the fov may be for predict where we may heading to, explain why vridge have black edge often

**Comment by ShootingKing-AM** [comment]
Should be solve with #54

**Comment by ShootingKing-AM** [comment]
This has been solved in latest release by using ALVR Server. If its not feel free to reopen the issue.
