### ISSUE TITLE
[Issue] Phone tracking works - no video

### ISSUE THREAD

**Issue by BitBlitObviMormon** [PhoneVR-Developers/PhoneVR#92]
## Issue
SteamVR detects the phone and enables tracking, but the phone has a black screen. I could launch a game in a window and see the viewport move when I tilt the phone, but nothing shows up on the phone itself. I double-checked that the video port was the same for both the server and the client, but it seems to check out ok. This issue is for the PhoneVR-0.2-beta_70 release.

## Phone Specs
Model: OnePlus Nord N200 5G
CPU: 2.0 GHz dual-core Kryo 460 Gold & 1.8GHz hexa-core Kryo 460 Silver
GPU: Adreno 619
Resolution: 2400 x 1080 (This is larger than my PC screen if that means anything)

## Logs
[pvrlog-phone.txt](https://github.com/ShootingKing-AM/PhoneVR/files/9074266/pvrlog-phone.txt)
[pvrlog-server.txt](https://github.com/ShootingKing-AM/PhoneVR/files/9074267/pvrlog-server.txt)
[vrserver.txt](https://github.com/ShootingKing-AM/PhoneVR/files/9074268/vrserver.txt)
[steamvr.vrsettings](https://github.com/ShootingKing-AM/PhoneVR/files/9074270/steamvr.txt) (I had to rename the file to .txt for GitHub to allow it)

**Comment by BitBlitObviMormon** [comment]
Possible duplicate of #55.

**Comment by BitBlitObviMormon** [comment]
Sure, give me a few days. I have to reinstall everything.

**Comment by ShootingKing-AM** [comment]
> Sure, give me a few days. I have to reinstall everything. Though I am curious how helpful the screenshots will be. It's just a completely black picture.

Oops. Okay. If "stats" are being rendered  it would be ndk/opengl issue, if "stats" and the straight line in middle are not being rendered then its android sdk issue.

**Comment by BitBlitObviMormon** [comment]
If you think it would be helpful I'd be willing to run any debug build you send me. You could add some extra logs to your code to see which process is failing on my phone.

**Comment by ShootingKing-AM** [comment]
> If you think it would be helpful I'd be willing to run any debug build you send me. You could add some extra logs to your code to see which process is failing on my phone.

Ah! Really thankful for your support. I actually reinstall-rebuild-rerun everything on my end after like 1year or so, but still it works fine for me. Thought notorious android-sdk changed some weird things. Will definitely ping you if some testing is required. Do join the discord group :)
