### ISSUE TITLE
How to use the Controller emulator Device feature?

### ISSUE THREAD

**Issue by Fancy2209** [PhoneVR-Developers/PhoneVR#94]
It's not explained anywhere, do I need a app? do i need a phone with a specific version of Android? how do I use it? Does it work with 2 phones as controllers?

**Comment by Fancy2209** [comment]
I understand now that this is from GoogleVR I'm sorry!

But could using it as a controller be supported?
Or could there be a app from PhoneVR for this?

**Comment by BitBlitObviMormon** [comment]
> But could using it as a controller be supported?

There are already apps out there that make your phone behave like a PC controller. PhoneVR is meant to make your phone behave like a VR headset _not a controller_. I doubt support for that would be added anytime soon. If you want one phone to be a headset and the other to be a controller I'd use different apps for each phone (and expect a **LOT** of lag).

**Comment by ShootingKing-AM** [comment]
Since @BitBlitObviMormon already answered it, am closing this as completed.
