### ISSUE TITLE
Phone VR working so slow

### ISSUE THREAD

**Issue by Sanjarbek17** [PhoneVR-Developers/PhoneVR#95]
Hi, PVR Devs, I am facing a crash with the following Error:

 ```ml
java.lang.SecurityException: Permission Denial: starting Intent { act=com.google.vrtoolkit.cardboard.CONFIGURE cmp=com.google.samples.apps.cardboarddemo/com.google.vr.cardboard.paperscope.carton.Settings } from ProcessRecord{a76970 31778:viritualisres.phonevr/u0a521} (pid=31778, uid=10521) not exported from uid 10185
```

You are doing a good job. Hope this helps ;)

**Comment by Sanjar1218** [comment]
i solved with change qp settings to 10 from 20

**Comment by BitBlitObviMormon** [comment]
> I solved with change qp settings to 10 from 20

If you solved it can you close the issue?

**Comment by Sanjar1218** [comment]
I'd happy to close it but it doesn't work i didn't solved it

**Comment by BitBlitObviMormon** [comment]
Ok. I'm not a dev, but you'll probably get a faster fix if you post the crash logs and other data listed in the [readme](https://github.com/ShootingKing-AM/PhoneVR/blob/master/README.md#issue--bug-reporting). (To be clear, what you submitted is not a log).

**Comment by ShootingKing-AM** [comment]
Yes please attach the required logs. I am confused too is it slow or is it a crash or is it two different issues ?

**Comment by Sanjar1218** [comment]
i don't where can i find log it was you was long time age but the problem was it does not crashing but working slow latency to high I guess. I have tried USB cable and wifi I have seen USB cable work well a little bit more than wifi but it is still too slow.  i have tried changing configurations. yesterday I have used it and it worked well I guess you guys fix it. alas there is some latency still. you can close this issue

**Comment by ShootingKing-AM** [comment]
This has been solved in latest release by using hardware encoding provided by ALVR Server. If its not feel free to reopen the issue.

**Comment by AccountTaken** [comment]
it just says this error and doest work
![imagem_2023-08-15_141325557](https://github.com/PhoneVR-Developers/PhoneVR/assets/142256499/f607af50-6168-4a1d-837a-08ac105d3d23)
