### ISSUE TITLE
Gyro stops working

### ISSUE THREAD

**Issue by LatvianVideo** [PhoneVR-Developers/PhoneVR#97]
Sometimes, when I connect my phone (xiaomi poco m3 pro 5g) to my laptop via usb and tethering and start steamvr, it takes the gyro position where it was when it launched, but doesnt move when I move my phone, rn the only way to fix that is to restart the phone.

**Comment by LatvianVideo** [comment]
[pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/10148293/pvrlog.txt)

**Comment by LatvianVideo** [comment]
from the phone: `12:53:50-04.12.2022 - PVR-JNI-I: --------------------------------------------------------------------------------
12:53:50-04.12.2022 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
12:53:51-04.12.2022 - PVR-JNI-I: --------------------------------------------------------------------------------
12:53:51-04.12.2022 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
12:53:51-04.12.2022 - PVR-JNI-I: JNI startAnnouncer: :33333
12:53:51-04.12.2022 - PVR-JNI-I: [TCPTalker::TCPTalker] Init'ed with p:33333 isServer:1 ip:
12:53:51-04.12.2022 - PVR-JNI-I: [TCPTalker::TCPTalker] Talker is Server and ip is Empty. Accepting All connection...
12:53:51-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[rndis0] desc=[unavailable] address=[192.168.165.23] netmask=[255.255.255.0] broadcastAddr=[192.168.165.255]
12:53:51-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[wlan0] desc=[unavailable] address=[192.168.8.112] netmask=[255.255.255.0] broadcastAddr=[192.168.8.255]
12:53:51-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[lo] desc=[unavailable] address=[127.0.0.1] netmask=[255.0.0.0] broadcastAddr=[127.255.255.255]
12:53:51-04.12.2022 - PVR-JNI-I: JNI stopAnnouncer
12:53:51-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStopAnnouncer] Stopping Announcer.
12:53:51-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStartAnnouncer::PVRAnnounceToAllInterfaces] Announcer Stopped.
12:53:52-04.12.2022 - PVR-JNI-I: --------------------------------------------------------------------------------
12:53:52-04.12.2022 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
12:53:52-04.12.2022 - PVR-JNI-I: --------------------------------------------------------------------------------
12:53:52-04.12.2022 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
12:53:52-04.12.2022 - PVR-JNI-I: JNI startAnnouncer: :33333
12:53:52-04.12.2022 - PVR-JNI-I: [TCPTalker::send] Error Sending: Socket is not open
12:53:52-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStartAnnouncer] TCPTalker error: Bad address
12:53:52-04.12.2022 - PVR-JNI-I: [TCPTalker::TCPTalker] Init'ed with p:33333 isServer:1 ip:
12:53:52-04.12.2022 - PVR-JNI-I: [TCPTalker::TCPTalker] Talker is Server and ip is Empty. Accepting All connection...
12:53:52-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[rndis0] desc=[unavailable] address=[192.168.165.23] netmask=[255.255.255.0] broadcastAddr=[192.168.165.255]
12:53:52-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[wlan0] desc=[unavailable] address=[192.168.8.112] netmask=[255.255.255.0] broadcastAddr=[192.168.8.255]
12:53:52-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[lo] desc=[unavailable] address=[127.0.0.1] netmask=[255.0.0.0] broadcastAddr=[127.255.255.255]
12:53:52-04.12.2022 - PVR-JNI-I: JNI stopAnnouncer
12:53:52-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStopAnnouncer] Stopping Announcer.
12:53:52-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStartAnnouncer::PVRAnnounceToAllInterfaces] Announcer Stopped.
12:54:32-04.12.2022 - PVR-JNI-I: --------------------------------------------------------------------------------
12:54:32-04.12.2022 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
12:54:32-04.12.2022 - PVR-JNI-I: JNI startAnnouncer: :33333
12:54:32-04.12.2022 - PVR-JNI-I: [TCPTalker::send] Error Sending: Socket is not open
12:54:32-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStartAnnouncer] TCPTalker error: Bad address
12:54:32-04.12.2022 - PVR-JNI-I: [TCPTalker::TCPTalker] Init'ed with p:33333 isServer:1 ip:
12:54:32-04.12.2022 - PVR-JNI-I: [TCPTalker::TCPTalker] Talker is Server and ip is Empty. Accepting All connection...
12:54:32-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[rndis0] desc=[unavailable] address=[192.168.165.23] netmask=[255.255.255.0] broadcastAddr=[192.168.165.255]
12:54:32-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[wlan0] desc=[unavailable] address=[192.168.8.112] netmask=[255.255.255.0] broadcastAddr=[192.168.8.255]
12:54:32-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[lo] desc=[unavailable] address=[127.0.0.1] netmask=[255.0.0.0] broadcastAddr=[127.255.255.255]
12:54:34-04.12.2022 - PVR-JNI-I: JNI stopAnnouncer
12:54:34-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStopAnnouncer] Stopping Announcer.
12:54:34-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStartAnnouncer::PVRAnnounceToAllInterfaces] Announcer Stopped.
12:54:36-04.12.2022 - PVR-JNI-I: --------------------------------------------------------------------------------
12:54:36-04.12.2022 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
12:54:36-04.12.2022 - PVR-JNI-I: JNI startAnnouncer: :33333
12:54:36-04.12.2022 - PVR-JNI-I: [TCPTalker::send] Error Sending: Socket is not open
12:54:36-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStartAnnouncer] TCPTalker error: Bad address
12:54:36-04.12.2022 - PVR-JNI-I: [TCPTalker::TCPTalker] Init'ed with p:33333 isServer:1 ip:
12:54:36-04.12.2022 - PVR-JNI-I: [TCPTalker::TCPTalker] Talker is Server and ip is Empty. Accepting All connection...
12:54:36-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[rndis0] desc=[unavailable] address=[192.168.165.23] netmask=[255.255.255.0] broadcastAddr=[192.168.165.255]
12:54:36-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[wlan0] desc=[unavailable] address=[192.168.8.112] netmask=[255.255.255.0] broadcastAddr=[192.168.8.255]
12:54:36-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[lo] desc=[unavailable] address=[127.0.0.1] netmask=[255.0.0.0] broadcastAddr=[127.255.255.255]
12:54:47-04.12.2022 - PVR-JNI-I: [TCPTalker::TCPTalker] Talker is Connected. Trying to read some data...
12:54:47-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStopAnnouncer] Stopping Announcer.
12:54:47-04.12.2022 - PVR-JNI-I: JNI callJavaMethod: Calling segueToGame
12:54:47-04.12.2022 - PVR-JNI-I: JNI_callJavaMethod:: JNI Not attached
12:54:47-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStartAnnouncer::PVRAnnounceToAllInterfaces] Announcer Stopped.
12:54:47-04.12.2022 - PVR-JNI-I: JNI stopAnnouncer
12:54:47-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStopAnnouncer] Stopping Announcer.
12:54:47-04.12.2022 - PVR-JNI-I: JNI createRenderer
12:54:47-04.12.2022 - PVR-JNI-I: JNI startSendSensorData 51423
12:54:47-04.12.2022 - PVR-JNI-I: JNI onResume
12:54:47-04.12.2022 - PVR-JNI-I: [TCPTalker::send] Msg Sent with ID:
12:54:52-04.12.2022 - PVR-JNI-I: Renderer::PVRPrintGLDesc: glVendor : ARM, glRenderer : Mali-G57 MC2, glVersion : OpenGL ES 3.2 v1.r32p1-00bet4.db4e5dfde7f7b9248ee3cb409f92ba0d
12:54:52-04.12.2022 - PVR-JNI-I: Renderer::PVRPrintGLDesc: glExts : GL_EXT_debug_marker, GL_ARM_rgba8, GL_ARM_mali_shader_binary, GL_OES_depth24, GL_OES_depth_texture, GL_OES_depth_texture_cube_map, GL_OES_packed_depth_stencil, GL_OES_rgb8_rgba8, GL_EXT_read_format_bgra, GL_OES_compressed_paletted_texture, GL_OES_compressed_ETC1_RGB8_texture, GL_OES_standard_derivatives, GL_OES_EGL_image, GL_OES_EGL_image_external, GL_OES_EGL_image_external_essl3, GL_OES_EGL_sync, GL_OES_texture_npot, GL_OES_vertex_half_float, GL_OES_required_internalformat, GL_OES_vertex_array_object, GL_OES_mapbuffer, GL_EXT_texture_format_BGRA8888, GL_EXT_texture_rg, GL_EXT_texture_type_2_10_10_10_REV, GL_OES_fbo_render_mipmap, GL_OES_element_index_uint, GL_EXT_shadow_samplers, GL_OES_texture_compression_astc, GL_KHR_texture_compression_astc_ldr, GL_KHR_texture_compression_astc_hdr, GL_KHR_texture_compression_astc_sliced_3d, GL_EXT_texture_compression_astc_decode_mode, GL_EXT_texture_compression_astc_decode_mode_rgb9e5, GL_KHR_debug, GL_EXT_occlusion_query_boolean, GL_EXT_disjoint_timer_query, GL_EXT_blend_minmax, GL_EXT_discard_framebuffer, GL_OES_get_program_binary, GL_OES_texture_3D, GL_EXT_texture_storage, GL_EXT_multisampled_render_to_texture, GL_EXT_multisampled_render_to_texture2, GL_OES_surfaceless_context, GL_OES_texture_stencil8, GL_EXT_shader_pixel_local_storage, GL_ARM_shader_framebuffer_fetch, GL_ARM_shader_framebuffer_fetch_depth_stencil, GL_ARM_mali_program_binary, GL_EXT_sRGB, GL_EXT_sRGB_write_control, GL_EXT_texture_sRGB_decode, GL_EXT_texture_sRGB_R8, GL_EXT_texture_sRGB_RG8, GL_KHR_blend_equation_advanced, GL_KHR_blend_equation_advanced_coherent, GL_OES_texture_storage_multisample_2d_array, GL_OES_shader_image_atomic, GL_EXT_robustness, GL_EXT_draw_buffers_indexed, GL_OES_draw_buffers_indexed, GL_EXT_texture_border_clamp, GL_OES_texture_border_clamp, GL_EXT_texture_cube_map_array, GL_OES_texture_cube_map_array, GL_OES_sample_variables, GL_OES_sample_shading, GL_OES_shader_multisample_interpolation, GL_EXT_shader_io_blocks, GL_OES_shader_io_blocks, GL_EXT_tessellation_shader, GL_OES_tessellation_shader, GL_EXT_primitive_bounding_box, GL_OES_primitive_bounding_box, GL_EXT_geometry_shader, GL_OES_geometry_shader, GL_ANDROID_extension_pack_es31a, GL_EXT_gpu_shader5, GL_OES_gpu_shader5, GL_EXT_texture_buffer, GL_OES_texture_buffer, GL_EXT_copy_image, GL_OES_copy_image, GL_EXT_shader_non_constant_global_initializers, GL_EXT_color_buffer_half_float, GL_EXT_unpack_subimage, GL_EXT_color_buffer_float, GL_EXT_float_blend, GL_EXT_YUV_target, GL_OVR_multiview, GL_OVR_multiview2, GL_OVR_multiview_multisampled_render_to_texture, GL_KHR_robustness, GL_KHR_robust_buffer_access_behavior, GL_EXT_draw_elements_base_vertex, GL_OES_draw_elements_base_vertex, GL_EXT_protected_textures, GL_EXT_buffer_storage, GL_EXT_external_buffer, GL_EXT_EGL_image_array, GL_EXT_texture_filter_anisotropic, GL_OES_texture_float_linear, GL_ARM_texture_unnormalized_coordinates, GL_EXT_shader_framebuffer_fetch, GL_MTK_texture_lod_bias, 
12:54:52-04.12.2022 - PVR-JNI-I: Renderer::PVRPrintGLDesc: glVendor : ARM, glRenderer : Mali-G57 MC2, glVersion : OpenGL ES 3.2 v1.r32p1-00bet4.db4e5dfde7f7b9248ee3cb409f92ba0d
12:54:52-04.12.2022 - PVR-JNI-I: Renderer::PVRPrintGLDesc: glExts : GL_EXT_debug_marker, GL_ARM_rgba8, GL_ARM_mali_shader_binary, GL_OES_depth24, GL_OES_depth_texture, GL_OES_depth_texture_cube_map, GL_OES_packed_depth_stencil, GL_OES_rgb8_rgba8, GL_EXT_read_format_bgra, GL_OES_compressed_paletted_texture, GL_OES_compressed_ETC1_RGB8_texture, GL_OES_standard_derivatives, GL_OES_EGL_image, GL_OES_EGL_image_external, GL_OES_EGL_image_external_essl3, GL_OES_EGL_sync, GL_OES_texture_npot, GL_OES_vertex_half_float, GL_OES_required_internalformat, GL_OES_vertex_array_object, GL_OES_mapbuffer, GL_EXT_texture_format_BGRA8888, GL_EXT_texture_rg, GL_EXT_texture_type_2_10_10_10_REV, GL_OES_fbo_render_mipmap, GL_OES_element_index_uint, GL_EXT_shadow_samplers, GL_OES_texture_compression_astc, GL_KHR_texture_compression_astc_ldr, GL_KHR_texture_compression_astc_hdr, GL_KHR_texture_compression_astc_sliced_3d, GL_EXT_texture_compression_astc_decode_mode, GL_EXT_texture_compression_astc_decode_mode_rgb9e5, GL_KHR_debug, GL_EXT_occlusion_query_boolean, GL_EXT_disjoint_timer_query, GL_EXT_blend_minmax, GL_EXT_discard_framebuffer, GL_OES_get_program_binary, GL_OES_texture_3D, GL_EXT_texture_storage, GL_EXT_multisampled_render_to_texture, GL_EXT_multisampled_render_to_texture2, GL_OES_surfaceless_context, GL_OES_texture_stencil8, GL_EXT_shader_pixel_local_storage, GL_ARM_shader_framebuffer_fetch, GL_ARM_shader_framebuffer_fetch_depth_stencil, GL_ARM_mali_program_binary, GL_EXT_sRGB, GL_EXT_sRGB_write_control, GL_EXT_texture_sRGB_decode, GL_EXT_texture_sRGB_R8, GL_EXT_texture_sRGB_RG8, GL_KHR_blend_equation_advanced, GL_KHR_blend_equation_advanced_coherent, GL_OES_texture_storage_multisample_2d_array, GL_OES_shader_image_atomic, GL_EXT_robustness, GL_EXT_draw_buffers_indexed, GL_OES_draw_buffers_indexed, GL_EXT_texture_border_clamp, GL_OES_texture_border_clamp, GL_EXT_texture_cube_map_array, GL_OES_texture_cube_map_array, GL_OES_sample_variables, GL_OES_sample_shading, GL_OES_shader_multisample_interpolation, GL_EXT_shader_io_blocks, GL_OES_shader_io_blocks, GL_EXT_tessellation_shader, GL_OES_tessellation_shader, GL_EXT_primitive_bounding_box, GL_OES_primitive_bounding_box, GL_EXT_geometry_shader, GL_OES_geometry_shader, GL_ANDROID_extension_pack_es31a, GL_EXT_gpu_shader5, GL_OES_gpu_shader5, GL_EXT_texture_buffer, GL_OES_texture_buffer, GL_EXT_copy_image, GL_OES_copy_image, GL_EXT_shader_non_constant_global_initializers, GL_EXT_color_buffer_half_float, GL_EXT_unpack_subimage, GL_EXT_color_buffer_float, GL_EXT_float_blend, GL_EXT_YUV_target, GL_OVR_multiview, GL_OVR_multiview2, GL_OVR_multiview_multisampled_render_to_texture, GL_KHR_robustness, GL_KHR_robust_buffer_access_behavior, GL_EXT_draw_elements_base_vertex, GL_OES_draw_elements_base_vertex, GL_EXT_protected_textures, GL_EXT_buffer_storage, GL_EXT_external_buffer, GL_EXT_EGL_image_array, GL_EXT_texture_filter_anisotropic, GL_OES_texture_float_linear, GL_ARM_texture_unnormalized_coordinates, GL_EXT_shader_framebuffer_fetch, GL_MTK_texture_lod_bias, 
12:54:52-04.12.2022 - PVR-JNI-I: JNI startMediaCodec
12:54:52-04.12.2022 - PVR-JNI-I: JNI MCodec th Setup...
12:54:52-04.12.2022 - PVR-JNI-I: JNI setVStreamPort - 15243
12:54:52-04.12.2022 - PVR-JNI-I: JNI startStream
12:54:52-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStartReceiveStreams] th started.. @p:15243
12:55:00-04.12.2022 - PVR-JNI-I: JNI onPause
12:55:00-04.12.2022 - PVR-JNI-I: --------------------------------------------------------------------------------
12:55:00-04.12.2022 - PVR-JNI-I: JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
12:55:00-04.12.2022 - PVR-JNI-I: JNI startAnnouncer: :33333
12:55:00-04.12.2022 - PVR-JNI-I: [TCPTalker::send] Msg Sent with ID:
12:55:00-04.12.2022 - PVR-JNI-I: [TCPTalker::TCPTalker] Init'ed with p:33333 isServer:1 ip:
12:55:00-04.12.2022 - PVR-JNI-I: [TCPTalker::TCPTalker] Talker is Server and ip is Empty. Accepting All connection...
12:55:00-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[rndis0] desc=[unavailable] address=[192.168.165.23] netmask=[255.255.255.0] broadcastAddr=[192.168.165.255]
12:55:00-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[wlan0] desc=[unavailable] address=[192.168.8.112] netmask=[255.255.255.0] broadcastAddr=[192.168.8.255]
12:55:00-04.12.2022 - PVR-JNI-I: [Ancr]      Found interface:  name=[lo] desc=[unavailable] address=[127.0.0.1] netmask=[255.0.0.0] broadcastAddr=[127.255.255.255]
12:55:01-04.12.2022 - PVR-JNI-I: JNI stopAll
12:55:01-04.12.2022 - PVR-JNI-I: JNI stopAnnouncer
12:55:01-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStopAnnouncer] Stopping Announcer.
12:55:01-04.12.2022 - PVR-JNI-I: [PVRSockets::PVRStartAnnouncer::PVRAnnounceToAllInterfaces] Announcer Stopped.`

**Comment by LatvianVideo** [comment]
this time phone restart didnt fix it

**Comment by Aman-Anas** [comment]
I can confirm that I experience this issue from time to time, the solution for me is to just close and reopen both the app and SteamVR until it magically works again.

**Comment by Aman-Anas** [comment]
I'm not entirely sure if this is the reason, but it fixed itself sometimes when I opened another app that displays sensors (Sensors Multitool), closed out of PhoneVR, and then closed the app and opened PhoneVR again. Maybe something just needs to be refreshed for grabbing sensor data from android.

**Comment by ShootingKing-AM** [comment]
Did you test this on newest verion of PhoneVr, this should be fixed with ALVR+PhoneVR v1
