### ISSUE TITLE
Feature suggestion: Reconnect button

### ISSUE THREAD

**Issue by Aman-Anas** [PhoneVR-Developers/PhoneVR#98]
Sometimes, I accidentally close PhoneVR and the only way to reconnect is to close and re-open SteamVR. It would be nice if there were a way to auto-reconnect in case of connection loss. I'd be interested in helping out, but I'm not really sure where to start (I guess this would have to be done on the SteamVR driver side?)

**Comment by ShootingKing-AM** [comment]
This as been solve in latest release by using ALVR Server backend.
